runinvehicles: true # Calculate speed when player is in a vehicle. Disabling this MAY improve performance if you are having problems
destroyplayerdataonleave: false #Delete a player's customization settings when they leave