main: enderbyteprograms.actionspeed.ActionSpeedMain
name: ActionSpeed
version: 1.5.1
api-version: 1.16
commands:
  speedometer:
    description: Actionbar Speedometer command
    aliases:
      - actionspeed
      - as
permissions:
  actionspeed.*:
    description: Allows all access to commands
    children:
      #Put all perms to true
      actionspeed.speedometer: true
      actionspeed.admin: true
  actionspeed.speedometer:
    description: Allows personal enabling and disabling of speedometer as well as modification of personal speedometer
    default: true
  actionspeed.admin:
    description: Allows force shutdown and re-starting ActionSpeed as well as viewing of data. You can also enable or disable other people's speedometers
    default: op